name: Build libvips

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:
    inputs:
      vips_version:
        description: 'VIPS version to build'
        required: false
        default: '8.17.1'

permissions:
  contents: write  # <---- THIS LINE DOES THE MAGIC

env:
  VIPS_VERSION: ${{ github.event.inputs.vips_version || '8.17.1' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run build script
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: Commit and push artifact to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add build/heroku-22.tar.gz
        git commit -m "chore: add build artifact heroku-22.tar.gz [skip ci]" || echo "Nothing to commit"
        git push origin ${{ github.ref_name }}
